### ISSUE TITLE
Questions about some problems and fixes ?

### ISSUE THREAD

**Issue by Gamerios** [ubruhin/python-dlogg#1]
Hello

**The dlogg-linux from h. r   not work anymore always get not logger tryed change many things in code etc but not work.**   you also not know why ?

**With your python it reads the logger.**

And is there a way to read out with your Python and like at Dlogg-Linux export to WinSol File Format Old version or if work new version have both :)

**_But the dlogg-db not work anymore cannot install it always hangs at pandas install :(_**

**And at this dlogg driver why no WMZ , SOLAR,  energy data, power data , or kwh or mWh is read out anymore ? Its comment out but when decomment i get only error what need todo ?**

`class Uvr1611Data(object):
    def __init__(self, raw_data, offset):
        self.raw = bytearray(raw_data)
        data = raw_data[offset:]
        self.inputs = list()
        for i in range(0, 16):
            self.inputs.append(InputData(data[i*2:i*2+2]))
        self.outputs = list()
        for i in range(0, 13):
            self.outputs.append(True if unpack("<H", data[32:34])[0] & 1 << i else False)
        self.pump_speeds = list()
        for i in range(0, 4):
            self.pump_speeds.append(PumpSpeed(data[34+i]))
        # self.wmz_active = raw_data[38]
        # self.solar_1_power = unpack(">I", raw_data[39:43])
        # self.solar_1_kwh = unpack(">H", raw_data[43:45])
        # self.solar_1_mwh = unpack(">H", raw_data[45:47])
        # self.solar_2_power = unpack(">I", raw_data[47:51])
        # self.solar_2_kwh = unpack(">H", raw_data[51:53])
        # self.solar_2_mwh = unpack(">H", raw_data[53:55])
        checksum = raw_data[-1]
        checksum_calc = sum(raw_data[0:-1]) & 0xFF
        if checksum != checksum_calc:
            raise IOError("Checksum mismatch in header")

    def __unicode__(self):
        text = u"{\n"
        text += u"  inputs:       {}\n".format(u", ".join([unicode(x) for x in self.inputs]))
        text += u"  outputs:      {}\n".format(u", ".join([unicode(x) for x in self.outputs]))
        text += u"  pump_speeds:  {}\n".format(u", ".join([unicode(x) for x in self.pump_speeds]))
        # text += u"  wmz_active: {}\n".format(self.wmz_active)
        # text += u"  solar_1_power: {}\n".format(self.solar_1_power)
        # text += u"  solar_1_kwh: {}\n".format(self.solar_1_kwh)
        # text += u"  solar_1_mwh: {}\n".format(self.solar_1_mwh)
        # text += u"  solar_2_power: {}\n".format(self.solar_2_power)
        # text += u"  solar_2_kwh: {}\n".format(self.solar_2_kwh)
        # text += u"  solar_2_mwh: {}\n".format(self.solar_2_mwh)
        return text`

**Its needed how can i read that out with your py ?** 

**Hope you can help me thanks.**

Regards

**Comment by ubruhin** [comment]
Hi!

> The dlogg-linux from h. r not work anymore always get not logger tryed change many things in code etc but not work. you also not know why ?

No, sorry, I also don't know why. But to be honest, the code of dlogg-linux is extremely ugly, so no surprise that it doesn't work properly ;)

> And is there a way to read out with your Python and like at Dlogg-Linux export to WinSol File Format Old version or if work new version have both :)

No, I don't use this file format so I didn't implement it. But maybe it's easy to create a CSV file and then convert it to WinSol with the dlogg-linux tools.

> And at this dlogg driver why no WMZ , SOLAR, energy data, power data , or kwh or mWh is read out anymore ? Its comment out but when decomment i get only error what need todo ?

Yeah the commented code is quite old, and it seems that some variable names and maybe also array indices are no longer correct. But I think it should be quite easy to make it working again, you may only need some try&error ;)

I'm sorry but at the moment I have no time to work on this anymore. But if you found a solution, please open a pull request, then I can merge it and upload the new version to pypi.

Regards

**Comment by Gamerios** [comment]
**Yeah i tryed but Dlogg can only from WinSol to CSV  but not from CSV to Winsol or so.**

**Need find a way   .. Also new WInSol format will be good / best  :(**

**Comment by ubruhin** [comment]
OK then I can't help you, sorry...
