### ISSUE TITLE
IOError: Received 63 bytes instead of 65

### ISSUE THREAD

**Issue by wolkenloseswetter** [ubruhin/python-dlogg#2]
Hi,
when i am trying to readout my logger with my raspberry pi, i get:

Type: Type.BL232_DLOGG_1DL
Firmware: 2.9
Mode: Mode.ONE_DL
Logging criterion: <dlogg_driver.definitions.LoggingCriterion object at 0x769db7b0>
Number of available samples: 32
Traceback (most recent call last):
  File "ou1.py", line 10, in <module>
    data = device.fetch_data_range(header.start, 1)
  File "/home/pi/.local/lib/python2.7/site-packages/dlogg_driver/device.py", line 94, in fetch_data_range
    data.append(self.fetch_data(addr))
  File "/home/pi/.local/lib/python2.7/site-packages/dlogg_driver/device.py", line 88, in fetch_data
    return Uvr1611MemoryData(self._transceive(tx_data, 65, checksum=True))
  File "/home/pi/.local/lib/python2.7/site-packages/dlogg_driver/device.py", line 125, in _transceive
    raise IOError("Received {} bytes instead of {}".format(len(rx_data), rx_len))
**_IOError: Received 63 bytes instead of 65_**

Any ideas?

Thanxs

**Comment by ubruhin** [comment]
Hi, unfortunately I have no idea what could went wrong. Could you post the script you used and the whole logging output (with logging level set to DEBUG so I can see what data was received)?

And does `get_current_data()` work properly?

**Comment by wolkenloseswetter** [comment]
Hi, 
thank you for helping me!

When I try to readout my UVR61-3 with D-LOGG USB i probably get the error at position 
`return Uvr1611CurrentData(self._transceive([Cmd.GET_CURRENT_DATA], 57))`

I receive from my logger only 55 bytes instead of 57.

**Here the script i use:**
```
import logging
logging.basicConfig(level=logging.DEBUG)

from dlogg_driver import DLoggDevice

with DLoggDevice("/dev/ttyUSB1") as device:
    print u"Type: {}".format(device.get_type())
    print u"Firmware: {}".format(device.get_firmware_version())
    print u"Mode: {}".format(device.get_mode())
    print u"Logging criterion: {}".format(unicode(device.get_logging_criterion()))
    print u"Current data: {}".format(unicode(device.get_current_data()))
    header = device.get_header()
    print u"Number of available samples: {}".format(header.get_sample_count())
    data = device.fetch_data_range(header.start, 1)
    print u"Data [0]: {}".format(unicode(data[0]))
    device.fetch_end()
```

**Here is the debug-log:**
INFO:dlogg_driver.device:Opened port /dev/ttyUSB1
DEBUG:dlogg_driver.device:Transceive: ['0x81'] --> ['0xa8']
INFO:dlogg_driver.device:Mode of connected device: Mode.ONE_DL
DEBUG:dlogg_driver.device:Transceive: ['0x20', '0x10', '0x18', '0x0', '0x0', '0x0', '0x0', '0x48'] --> ['0x21', '0x43', '0xa8', '0x1d', '0xc5']
Type: Type.BL232_DLOGG_1DL
DEBUG:dlogg_driver.device:Transceive: ['0x82'] --> ['0x1d']
Firmware: 2.9
DEBUG:dlogg_driver.device:Transceive: ['0x81'] --> ['0xa8']
Mode: Mode.ONE_DL
DEBUG:dlogg_driver.device:Transceive: ['0x95'] --> ['0x95', '0x83', '0x18']
Logging criterion: 60.0s
DEBUG:dlogg_driver.device:Transceive: ['0xab'] --> ['0x90', '0xcf', '0x21', '0xeb', '0x21', '0x7e', '0x22', '0x23', '0x22', '0xff', '0x2f', '0xff', '0x2f', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x80', '0x80', '0x1', '0x0', '0x0', '0x1a', '0x2', '0x6', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0xf0']
INFO:dlogg_driver.device:Closed port /dev/ttyUSB1
Traceback (most recent call last):
  File "read_d-logg.py", line 12, in <module>
    print u"Current data: {}".format(unicode(device.get_current_data()))
  File "/home/pi/.local/lib/python2.7/site-packages/dlogg_driver/device.py", line 82, in get_current_data
    return Uvr1611CurrentData(self._transceive([Cmd.GET_CURRENT_DATA], 57))
  File "/home/pi/.local/lib/python2.7/site-packages/dlogg_driver/device.py", line 126, in _transceive
    raise IOError("Received {} bytes instead of {}".format(len(rx_data), rx_len))
IOError: Received 55 bytes instead of 57

**Comment by ubruhin** [comment]
Ah, according the received data it seems that your device is a UVR61-3, not a UVR1611. Unfortunately this driver currently only supports UVR1611 devices, the UVR61-3 uses another data format so it doesn't work...

If you're interested in contributing the UVR61-3 support to this driver, please let me know :)

**Comment by wolkenloseswetter** [comment]
Thanks. Now I got a version of 'dl-aktuelle-datenx' going. At least I receive some temperatures but no solar power data.
